[project]
name = "personal-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.53.0",
    "scipy>=1.17.0",
    "sounddevice>=0.5.3",
    "faster-whisper>=1.2.1",
]
